"""add type_id to appointments

Revision ID: 8bcd500f9c65
Revises: fdf89893a0df
Create Date: 2026-02-05 10:42:12.152897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcd500f9c65'
down_revision: Union[str, Sequence[str], None] = 'fdf89893a0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_appointments_type_id'), 'appointments', ['type_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'appointment_types', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_type_id'), table_name='appointments')
    op.drop_column('appointments', 'type_id')
    # ### end Alembic commands ###
